In [31]:
#page 33 - 44

In [2]:
a = ["0",1,"two", "3",4]
a

['0', 1, 'two', '3', 4]

In [3]:
a[0]

'0'

In [4]:
a[1]

1

In [5]:
a[2]

'two'

In [6]:
import numpy as np

In [7]:
a = [0,1,2,3,4] # bertipe data list
a_numpy_array = np.array(a) # mengubah a menjadi Numpy array

In [14]:
a #tipe list

[0, 1, 2, 3, 4]

In [13]:
a_numpy_array #tipe numpy array

array([0, 1, 2, 3, 4])

In [11]:
a_numpy_array.dtype

dtype('int32')

In [12]:
type(a_numpy_array)

numpy.ndarray

# method pada numpy

In [15]:
#size
a_numpy_array.size #panjang data

5

In [17]:
a_numpy_array.ndim #dimensi

1

In [19]:
a_numpy_array.shape

(5,)

In [21]:
b = [3.1,11.02, 6.2,213.2,5.1]
b

[3.1, 11.02, 6.2, 213.2, 5.1]

In [23]:
b_numpy_array = np.array(b)
b_numpy_array

array([  3.1 ,  11.02,   6.2 , 213.2 ,   5.1 ])

In [24]:
type(b_numpy_array)

numpy.ndarray

In [25]:
b_numpy_array.dtype

dtype('float64')

In [26]:
#c langsung diisi numpy array

c = np.array([20,1,2,3,4])
c

array([20,  1,  2,  3,  4])

In [27]:
#mengubah data berdasarkan index
c[0]=100
c

array([100,   1,   2,   3,   4])

In [28]:
c[4]=0
c

array([100,   1,   2,   3,   0])

In [30]:
c[3:5]=300,400
c

array([100,   1,   2, 300, 400])